version: '3'
services:
  web:
    image: python:latest
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: python app.py
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: dibimbing_id
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
